GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "username" : "federer",
    "timeRecord": 1.2223,
    "gameSelected": 1
}

###
GET https://findwaldobackend.onrender.com